<?php


function rb_register_posts_and_taxonomy () {
	register_post_type( 'slider', array(
		'labels' => array(
			'name'               => 'Слайдер',
			'singular_name'      => 'Слайдер',
			'add_new'            => 'Добавить новый слайд',
			'add_new_item'       => 'Добавить новый слайд',
			'edit_item'          => 'Редактировать слайд',
			'new_item'           => 'Новый слайд',
			'view_item'          => 'Смотреть слайд',
			'search_items'       => 'Искать слайды',
			'not_found'          => 'Не найдено слайдов',
			'not_found_in_trash' => 'Слайдов в корзине не найден',
			'all_items'          => 'Все слайды',
		),
		'description'         => '',
		'public'              => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 5,
		'menu_icon'           => 'dashicons-images-alt',
		'hierarchical'        => false,
		'supports'            => array( 'title', 'revisions' ),
		'has_archive'         => false,
		'publicly_queryable'  => false,
		'show_in_rest'		  => false,
		'exclude_from_search' => true,
	));

	register_post_type( 'doctors', array(
		'labels' => array(
			'name'               => 'Специалисты',
			'singular_name'      => 'Специалист',
			'add_new'            => 'Добавить нового специалиста',
			'add_new_item'       => 'Добавить нового специалиста',
			'edit_item'          => 'Редактировать специалиста',
			'new_item'           => 'Новый специалист',
			'view_item'          => 'Просмотреть специалиста',
			'search_items'       => 'Искать специалиста',
			'not_found'          => 'Не найдено специалистов',
			'not_found_in_trash' => 'Специалистов в корзине не найдено',
			'all_items'          => 'Все специалисты',
		),
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 6,
		'menu_icon'           => 'dashicons-groups',
		'hierarchical'        => false,
		'supports'            => array( 'title', 'thumbnail', 'revisions' ),
		'taxonomies'          => array( 'departments' ),
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_in_rest'		  => false,
	) );


	register_taxonomy( 'departments', array( 'doctors' ), array(
			'name' 		=> 'Направления',
			'label' 	=> 'Направления',
			'labels'	=> array(
					'name' 							=> 'Направления',
					'singular_name' 				=> 'Направления',
					'search_items' 					=> 'Поиск направления',
					'popular_items' 				=> 'Популярные направления',
					'all_items' 					=> 'Все направления',
					'parent_item' 					=> 'Родительское направление',
					'parent_item_colon' 			=> 'Родительское направление',
					'edit_item' 					=> 'Редактировать направление',
					'view_item' 					=> 'Просмотреть направление',
					'update_item' 					=> 'Обновить направление',
					'add_new_item'					=> 'Добавить новое направление',
					'new_item_name' 				=> 'Имя нового направления',
					'separate_items_with_commas' 	=> 'Разделяйте направления запятыми',
					'add_or_remove_items' 			=> 'Добавить или удалить направления',
					'choose_from_most_used'			=> 'Выберите из наиболее используемых направлений',
					'not_found' 					=> 'Направлений не найдено.',
					'no_terms' 						=> 'Направлений нет',
					'items_list_navigation' 		=> 'Навигация по списку направлений',
					'items_list' 					=> 'Список направлений',
					'most_used' 					=> 'Часто используемые направления',
					'back_to_items' 				=> '← Назад к направлениям',
					'menu_name' 					=> 'Направления',
					'name_admin_bar' 				=> 'Направления',
					'archives' 						=> 'Все направления',
			),
		'public' => true,
		'publicly_queryable' => true,
		'hierarchical' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => true,
		'show_in_quick_edit' => true,
		'show_admin_column' => true,
	));


	register_post_type( 'service', array(
		'labels' => array(
			'name'               => 'Услуги',
			'singular_name'      => 'Услуги',
			'add_new'            => 'Добавить новую услугу',
			'add_new_item'       => 'Добавить новую услугу',
			'edit_item'          => 'Редактировать услугу',
			'new_item'           => 'Новая услуга',
			'view_item'          => 'Просмотреть услугу',
			'search_items'       => 'Искать услугу',
			'not_found'          => 'Не найдено услуг',
			'not_found_in_trash' => 'Услуг в корзине не найдено',
			'all_items'          => 'Все услуги',
		),
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 7,
		'menu_icon'           => 'dashicons-heart',
		'hierarchical'        => false,
		'supports'            => array( 'title', 'thumbnail', 'revisions' ),
		'taxonomies'          => array( 'services' ),
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_in_rest'		  => false,
		// 'rewrite' => array(
		// 	'slug' => 'service-item',
		// ),
	) );
	
	register_taxonomy( 'services', array( 'service' ), array(
			'name' 		=> 'Направления',
			'label' 	=> 'Направления',
			'labels'	=> array(
					'name' 							=> 'Направления',
					'singular_name' 				=> 'Направления',
					'search_items' 					=> 'Поиск направления',
					'popular_items' 				=> 'Популярные направления',
					'all_items' 					=> 'Все направления',
					'parent_item' 					=> 'Родительское направление',
					'parent_item_colon' 			=> 'Родительское направление',
					'edit_item' 					=> 'Редактировать направление',
					'view_item' 					=> 'Просмотреть направление',
					'update_item' 					=> 'Обновить направление',
					'add_new_item'					=> 'Добавить новое направление',
					'new_item_name' 				=> 'Имя нового направления',
					'separate_items_with_commas' 	=> 'Разделяйте направления запятыми',
					'add_or_remove_items' 			=> 'Добавить или удалить направления',
					'choose_from_most_used'			=> 'Выберите из наиболее используемых направлений',
					'not_found' 					=> 'Направлений не найдено.',
					'no_terms' 						=> 'Направлений нет',
					'items_list_navigation' 		=> 'Навигация по списку направлений',
					'items_list' 					=> 'Список направлений',
					'most_used' 					=> 'Часто используемые направления',
					'back_to_items' 				=> '← Назад к направлениям',
					'menu_name' 					=> 'Направления',
					'name_admin_bar' 				=> 'Направления',
					'archives' 						=> 'Все направления',
			),
		'public' => true,
		'publicly_queryable' => true,
		'hierarchical' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => true,
		'show_in_quick_edit' => true,
		'show_admin_column' => true,
		// 'rewrite' => array(
		// 	'slug' => 'service',
		// ),
	));

	register_post_type( 'programms', array(
		'labels' => array(
			'name'               => 'Программы',
			'singular_name'      => 'Программы',
			'add_new'            => 'Добавить новую программу',
			'add_new_item'       => 'Добавить новую программу',
			'edit_item'          => 'Редактировать программу',
			'new_item'           => 'Новая программа',
			'view_item'          => 'Просмотреть программу',
			'search_items'       => 'Искать программу',
			'not_found'          => 'Не найдено программ',
			'not_found_in_trash' => 'Программ в корзине не найдено',
			'all_items'          => 'Все программы',
		),
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 8,
		'menu_icon'           => 'dashicons-welcome-write-blog',
		'hierarchical'        => true,
		'supports'            => array( 'title', 'editor', 'thumbnail', 'revisions', 'page-attributes' ),
		'taxonomies'          => array( 'programms-type' ),
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_in_rest'		  => false,
		'rewrite'			  => array(  
			// 'slug'=>'/programms-type',
			// 'with_front' => false
		), // свой слаг в URL
	) );

	register_taxonomy( 'programms-type', array( 'programms' ), array(
			'name' 		=> 'Тип программы',
			'label' 	=> 'Тип программы',
			'labels'	=> array(
					'name' 							=> 'Тип программы',
					'singular_name' 				=> 'Тип программы',
					'search_items' 					=> 'Поиск типа программы',
					'popular_items' 				=> 'Популярные типы программ',
					'all_items' 					=> 'Все типы программ',
					'parent_item' 					=> 'Родительский тип',
					'parent_item_colon' 			=> 'Родительский тип',
					'edit_item' 					=> 'Редактировать тип программ',
					'view_item' 					=> 'Просмотреть тип программ',
					'update_item' 					=> 'Обновить тип программ',
					'add_new_item'					=> 'Добавить новый тип программ',
					'new_item_name' 				=> 'Имя нового типа программ',
					'separate_items_with_commas' 	=> 'Разделяйте типы программ запятыми',
					'add_or_remove_items' 			=> 'Добавить или удалить типы программ',
					'choose_from_most_used'			=> 'Выберите из наиболее используемых типов программ',
					'not_found' 					=> 'Типов программ не найдено.',
					'no_terms' 						=> 'Типов программ нет',
					'items_list_navigation' 		=> 'Навигация по списку типов программ',
					'items_list' 					=> 'Список типов программ',
					'most_used' 					=> 'Часто используемые типы программ',
					'back_to_items' 				=> '← Назад к типам программ',
					'menu_name' 					=> 'Тип программы',
					'name_admin_bar' 				=> 'Тип программы',
					'archives' 						=> 'Все типы программ',
			),
		'public' => false,
		'publicly_queryable' => false,
		'hierarchical' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => true,
		'show_in_quick_edit' => true,
		'show_admin_column' => true,
		//'rewrite'=> array( 'slug' => '.' ), // свой слаг в URL
	));

	register_post_type( 'videos', array(
		'labels' => array(
			'name'               => 'Видео',
			'singular_name'      => 'Видео',
			'add_new'            => 'Добавить новое видео',
			'add_new_item'       => 'Добавить новое видео',
			'edit_item'          => 'Редактировать видео',
			'new_item'           => 'Новое видео',
			'view_item'          => 'Просмотреть видео',
			'search_items'       => 'Искать видео',
			'not_found'          => 'Не найдено видео',
			'not_found_in_trash' => 'Видео в корзине не найдено',
			'all_items'          => 'Все видео',
		),
		'public'              => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 9,
		'menu_icon'           => 'dashicons-video-alt2',
		'hierarchical'        => false,
		'supports'            => array( 'title', 'thumbnail', 'revisions' ),
		'taxonomies'          => array( 'videos-type' ),
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => false,
		'show_in_rest'		  => false,
	) );

	register_taxonomy( 'videos-type', array( 'videos' ), array(
			'name' 		=> 'Тип видео',
			'label' 	=> 'Тип видео',
			'labels'	=> array(
					'name' 							=> 'Тип видео',
					'singular_name' 				=> 'Тип видео',
					'search_items' 					=> 'Поиск типа видео',
					'popular_items' 				=> 'Популярные типы видео',
					'all_items' 					=> 'Все типы видео',
					'parent_item' 					=> 'Родительский тип',
					'parent_item_colon' 			=> 'Родительский тип',
					'edit_item' 					=> 'Редактировать тип видео',
					'view_item' 					=> 'Просмотреть тип видео',
					'update_item' 					=> 'Обновить тип видео',
					'add_new_item'					=> 'Добавить новый тип видео',
					'new_item_name' 				=> 'Имя нового типа видео',
					'separate_items_with_commas' 	=> 'Разделяйте типы видео запятыми',
					'add_or_remove_items' 			=> 'Добавить или удалить типы видео',
					'choose_from_most_used'			=> 'Выберите из наиболее используемых типов видео',
					'not_found' 					=> 'Типов видео не найдено.',
					'no_terms' 						=> 'Типов видео нет',
					'items_list_navigation' 		=> 'Навигация по списку типов видео',
					'items_list' 					=> 'Список типов видео',
					'most_used' 					=> 'Часто используемые типы видео',
					'back_to_items' 				=> '← Назад к типам видео',
					'menu_name' 					=> 'Тип видео',
					'name_admin_bar' 				=> 'Тип видео',
					'archives' 						=> 'Все типы видео',
			),
		'public' => false,
		'publicly_queryable' => false,
		'hierarchical' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => true,
		'show_in_quick_edit' => true,
		'show_admin_column' => true,
		//'rewrite'=> array( 'slug' => '.' ), // свой слаг в URL
	));

	register_post_type( 'bio-market', array(
		'labels' => array(
			'name'               => 'Товары',
			'singular_name'      => 'Товары',
			'add_new'            => 'Добавить новый товар',
			'add_new_item'       => 'Добавить новый товар',
			'edit_item'          => 'Редактировать товар',
			'new_item'           => 'Новый товар',
			'view_item'          => 'Просмотреть товар',
			'search_items'       => 'Искать товар',
			'not_found'          => 'Не найдено товаров',
			'not_found_in_trash' => 'Товаров в корзине не найдено',
			'all_items'          => 'Все товары',
		),
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 9,
		'menu_icon'           => 'dashicons-cart',
		'hierarchical'        => false,
		'supports'            => array( 'title', 'editor', 'thumbnail', 'revisions' ),
		// 'taxonomies'          => array( 'promo' ),
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_in_rest'		  => false,
	) );

	register_post_type( 'reviews', array(
		'labels' => array(
			'name'               => 'Отзывы',
			'singular_name'      => 'Отзывы',
			'add_new'            => 'Добавить новый отзыв',
			'add_new_item'       => 'Добавить новый отзыв',
			'edit_item'          => 'Редактировать отзыв',
			'new_item'           => 'Новый отзыв',
			'view_item'          => 'Просмотреть отзыв',
			'search_items'       => 'Искать отзыв',
			'not_found'          => 'Не найдено отзывов',
			'not_found_in_trash' => 'Отзывов в корзине не найдено',
			'all_items'          => 'Все отзывы',
		),
		'public'              => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 10,
		'menu_icon'           => 'dashicons-megaphone',
		'hierarchical'        => false,
		'supports'            => array( 'title', 'editor', 'revisions' ),
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => false,
		'show_in_rest'		  => false,
	) );

	register_post_type( 'center-services', array(
		'labels' => array(
			'name'               => 'Услуги центра',
			'singular_name'      => 'Услуги центра',
			'add_new'            => 'Добавить новую услугу',
			'add_new_item'       => 'Добавить новую услугу',
			'edit_item'          => 'Редактировать услугу',
			'new_item'           => 'Новая услуга центра',
			'view_item'          => 'Просмотреть услугу центра',
			'search_items'       => 'Искать услугу центра',
			'not_found'          => 'Не найдено услуг центра',
			'not_found_in_trash' => 'Услугцентра в корзине не найдено',
			'all_items'          => 'Все услуги центра',
		),
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 11,
		'menu_icon'           => 'dashicons-store',
		'hierarchical'        => false,
		'supports'            => array( 'title', 'thumbnail', 'revisions', 'page-attributes' ),
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_in_rest'		  => false,
	) );

	register_post_type( 'video-doctors', array(
		'labels' => array(
			'name'               => 'Видео д/врачей',
			'singular_name'      => 'Видео д/врачей',
			'add_new'            => 'Добавить новое видео',
			'add_new_item'       => 'Добавить новое видео',
			'edit_item'          => 'Редактировать видео',
			'new_item'           => 'Новое видео',
			'view_item'          => 'Просмотреть видео',
			'search_items'       => 'Искать видео',
			'not_found'          => 'Не найдено видео',
			'not_found_in_trash' => 'Видео в корзине не найдено',
			'all_items'          => 'Все видео д/врачей',
		),
		'public'              => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 12,
		'menu_icon'           => 'dashicons-video-alt',
		'hierarchical'        => false,
		'supports'            => array( 'title', 'thumbnail', 'revisions' ),
		'taxonomies'          => array( 'video-cats' ),
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => false,
		'show_in_rest'		  => false,
	) );

	register_taxonomy( 'video-cats', array( 'video-doctors' ), array(
			'name' 		=> 'Направление видео',
			'label' 	=> 'Направление видео',
			'labels'	=> array(
					'name' 							=> 'Направление видео',
					'singular_name' 				=> 'Направление видео',
					'search_items' 					=> 'Поиск направления видео',
					'popular_items' 				=> 'Популярные направления видео',
					'all_items' 					=> 'Все направления видео',
					'parent_item' 					=> 'Родительский тип',
					'parent_item_colon' 			=> 'Родительский тип',
					'edit_item' 					=> 'Редактировать направления',
					'view_item' 					=> 'Просмотреть направления',
					'update_item' 					=> 'Обновить направления',
					'add_new_item'					=> 'Добавить новый направления',
					'new_item_name' 				=> 'Имя нового направления',
					'separate_items_with_commas' 	=> 'Разделяйте направления запятыми',
					'add_or_remove_items' 			=> 'Добавить или удалить направлений',
					'choose_from_most_used'			=> 'Выберите из наиболее используемых направлений',
					'not_found' 					=> 'Направления видео не найдено.',
					'no_terms' 						=> 'Направления видео нет',
					'items_list_navigation' 		=> 'Навигация по списку направлений видео',
					'items_list' 					=> 'Список направлений видео',
					'most_used' 					=> 'Часто используемые направления видео',
					'back_to_items' 				=> '← Назад к направлениям видео',
					'menu_name' 					=> 'Направления видео',
					'name_admin_bar' 				=> 'Направления видео',
					'archives' 						=> 'Все типы программ',
			),
		'public' => true,
		'publicly_queryable' => true,
		'hierarchical' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => true,
		'show_in_quick_edit' => true,
		'show_admin_column' => true,
		'rewrite'=> array( 'slug' => 'video' ), // свой слаг в URL
	));

	register_post_type( 'promo', array(
		'labels' => array(
			'name'               => 'Акции',
			'singular_name'      => 'Акция',
			'add_new'            => 'Добавить новую акцию',
			'add_new_item'       => 'Добавить новую акцию',
			'edit_item'          => 'Редактировать акцию',
			'new_item'           => 'Новая акция',
			'view_item'          => 'Просмотреть акцию',
			'search_items'       => 'Искать акцию',
			'not_found'          => 'Не найдено акций',
			'not_found_in_trash' => 'Акций в корзине не найдено',
			'all_items'          => 'Все акции',
		),
		'public'              => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 13,
		'menu_icon'           => 'dashicons-bell',
		'hierarchical'        => false,
		'supports'            => array( 'title', 'thumbnail', 'revisions' ),
		'taxonomies'          => array( 'promo-cat' ),
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => false,
		'show_in_rest'		  => false,
	) );


	register_taxonomy( 'promo-cat', array( 'promo' ), array(
			'name' 		=> 'Тип акции',
			'label' 	=> 'Тип акции',
			'labels'	=> array(
					'name' 							=> 'Тип акций',
					'singular_name' 				=> 'Тип акции',
					'search_items' 					=> 'Поиск типов акций',
					'popular_items' 				=> 'Популярные типы акций',
					'all_items' 					=> 'Все типы акций',
					'parent_item' 					=> 'Родительский тип',
					'parent_item_colon' 			=> 'Родительский тип',
					'edit_item' 					=> 'Редактировать тип',
					'view_item' 					=> 'Просмотреть тип',
					'update_item' 					=> 'Обновить тип',
					'add_new_item'					=> 'Добавить новый тип',
					'new_item_name' 				=> 'Имя нового типа',
					'separate_items_with_commas' 	=> 'Разделяйте типы акций запятыми',
					'add_or_remove_items' 			=> 'Добавить или удалить типы акций',
					'choose_from_most_used'			=> 'Выберите из наиболее используемых типов акций',
					'not_found' 					=> 'Типов акций не найдено.',
					'no_terms' 						=> 'Типов акций нет',
					'items_list_navigation' 		=> 'Навигация по списку типов акций',
					'items_list' 					=> 'Список типов акций',
					'most_used' 					=> 'Часто используемые типы акций',
					'back_to_items' 				=> '← Назад к типам акций',
					'menu_name' 					=> 'Тип акции',
					'name_admin_bar' 				=> 'Тип акции',
					'archives' 						=> 'Все типы акций',
			),
		'public' => true,
		'publicly_queryable' => true,
		'hierarchical' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => true,
		'show_in_quick_edit' => true,
		'show_admin_column' => true,
	));

	register_post_type( 'events', array(
		'labels' => array(
			'name'               => 'Мероприятия',
			'singular_name'      => 'Мероприятие',
			'add_new'            => 'Добавить новое мероприятие',
			'add_new_item'       => 'Добавить новое мероприятие',
			'edit_item'          => 'Редактировать мероприятие',
			'new_item'           => 'Новое мероприятие',
			'view_item'          => 'Просмотреть мероприятие',
			'search_items'       => 'Искать мероприятие',
			'not_found'          => 'Не найдено мероприятий',
			'not_found_in_trash' => 'Мероприятий в корзине не найдено',
			'all_items'          => 'Все мероприятия',
		),
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 6,
		'menu_icon'           => 'dashicons-format-status',
		'hierarchical'        => false,
		'supports'            => array( 'title', 'revisions', 'thumbnail' ),
		'taxonomies'          => array( 'events-type' ),
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => false,
		'show_in_rest'		  => false,
	) );


	register_taxonomy( 'events-type', array( 'events' ), array(
			'name' 		=> 'Направления',
			'label' 	=> 'Направления',
			'labels'	=> array(
					'name' 							=> 'Направления',
					'singular_name' 				=> 'Направления',
					'search_items' 					=> 'Поиск направления',
					'popular_items' 				=> 'Популярные направления',
					'all_items' 					=> 'Все направления',
					'parent_item' 					=> 'Родительское направление',
					'parent_item_colon' 			=> 'Родительское направление',
					'edit_item' 					=> 'Редактировать направление',
					'view_item' 					=> 'Просмотреть направление',
					'update_item' 					=> 'Обновить направление',
					'add_new_item'					=> 'Добавить новое направление',
					'new_item_name' 				=> 'Имя нового направления',
					'separate_items_with_commas' 	=> 'Разделяйте направления запятыми',
					'add_or_remove_items' 			=> 'Добавить или удалить направления',
					'choose_from_most_used'			=> 'Выберите из наиболее используемых направлений',
					'not_found' 					=> 'Направлений не найдено.',
					'no_terms' 						=> 'Направлений нет',
					'items_list_navigation' 		=> 'Навигация по списку направлений',
					'items_list' 					=> 'Список направлений',
					'most_used' 					=> 'Часто используемые направления',
					'back_to_items' 				=> '← Назад к направлениям',
					'menu_name' 					=> 'Направления',
					'name_admin_bar' 				=> 'Направления',
					'archives' 						=> 'Все направления',
			),
		'public' => true,
		'publicly_queryable' => true,
		'hierarchical' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'show_in_nav_menus' => true,
		'show_in_quick_edit' => true,
		'show_admin_column' => true,
	));


register_post_type( 'rb_author', array(
		'labels' => array(
			'name'               => 'Авторы',
			'singular_name'      => 'Автор',
			'add_new'            => 'Добавить автора',
			'add_new_item'       => 'Добавить нового автора',
			'edit_item'          => 'Редактировать автора',
			'new_item'           => 'Новый автор',
			'view_item'          => 'Просмотреть автора',
			'search_items'       => 'Поиск авторов',
			'not_found'          => 'Авторы не найдены',
			'not_found_in_trash' => 'В корзине авторов нет',
			'all_items'          => 'Все авторы',
		),
		'public'              => false,   // нет отдельных страниц авторов на фронте
		'publicly_queryable'  => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 14,
		'menu_icon'           => 'dashicons-admin-users',
		'hierarchical'        => false,
		'supports'            => array( 'title', 'thumbnail' ), // Заголовок = имя, миниатюра = фото
		'has_archive'         => false,
		'exclude_from_search' => true,
		'show_in_rest'        => false,
		'rewrite'             => false,
		'capability_type'     => 'post',
	) );
};

add_action( 'init', 'rb_register_posts_and_taxonomy' );
